-- EXPLORATORY DATA ANALYSIS

SELECT *
FROM LAYOFFS_STAGING2;

SELECT MAX(TOTAL_LAID_OFF), MAX(PERCENTAGE_LAID_OFF)
FROM LAYOFFS_STAGING2;

SELECT *
FROM LAYOFFS_STAGING2
WHERE PERCENTAGE_LAID_OFF = 1
ORDER BY TOTAL_LAID_OFF DESC;


SELECT *
FROM LAYOFFS_STAGING2
WHERE PERCENTAGE_LAID_OFF = 1
ORDER BY FUNDS_RAISED_MILLIONS DESC;

SELECT COMPANY, SUM(TOTAL_LAID_OFF) FROM layoffs_staging2
GROUP BY COMPANY
ORDER BY 2 DESC;

SELECT MIN(`DATE`), MAX(`DATE`)
FROM layoffs_staging2; 

SELECT INDUSTRY, SUM(TOTAL_LAID_OFF) FROM layoffs_staging2
GROUP BY industry
ORDER BY 2 DESC;

SELECT COUNTRY, SUM(TOTAL_LAID_OFF) FROM layoffs_staging2
GROUP BY COUNTRY
ORDER BY 2 DESC;

SELECT `DATE`, SUM(TOTAL_LAID_OFF) FROM layoffs_staging2
GROUP BY `DATE`
ORDER BY 2 DESC;

SELECT YEAR(`DATE`), SUM(TOTAL_LAID_OFF) FROM layoffs_staging2
GROUP BY YEAR(`DATE`)
ORDER BY 1 DESC;


SELECT STAGE, SUM(TOTAL_LAID_OFF) FROM layoffs_staging2
GROUP BY STAGE
ORDER BY 2 DESC;

SELECT SUBSTRING(`DATE`,1,7) AS `MONTH`, SUM(TOTAL_LAID_OFF)
FROM LAYOFFS_STAGING2
WHERE SUBSTRING(`DATE`,1,7) IS NOT NULL
GROUP BY `MONTH`
ORDER BY 1
;

WITH ROLLING_TOTAL AS
(
SELECT SUBSTRING(`DATE`,1,7) AS `MONTH`,
SUM(TOTAL_LAID_OFF) AS TOTAL_OFF
FROM LAYOFFS_STAGING2
WHERE SUBSTRING(`DATE`,1,7) IS NOT NULL
GROUP BY `MONTH`
ORDER BY 1
)
SELECT `MONTH`, TOTAL_OFF, SUM(TOTAL_OFF) OVER(ORDER BY `MONTH`) AS ROLLING_TOTAL
FROM ROLLING_TOTAL;

SELECT COMPANY, YEAR(`DATE`), SUM(TOTAL_LAID_OFF)
FROM LAYOFFS_staging2
GROUP BY COMPANY, YEAR(`DATE`)
ORDER BY 3 DESC;

WITH COMPANY_YEAR(COMPANY,YEARS, TOTAL_LAID_OFF) AS
(

SELECT COMPANY, YEAR(`DATE`), SUM(TOTAL_LAID_OFF)
FROM LAYOFFS_staging2
GROUP BY COMPANY, YEAR(`DATE`)
),
COMPANY_YEAR_RANK AS
(
SELECT *,
DENSE_RANK() OVER (PARTITION BY YEARS ORDER BY TOTAL_LAID_OFF DESC) AS RANKING
FROM COMPANY_YEAR
WHERE YEARS IS NOT NULL
)
SELECT *
FROM COMPANY_YEAR_RANK
WHERE RANKING <=5
;